[package]
name = "rb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
mongodb = "2.5.0"
serde = "1.0.162"
futures = "0.3.28"
bson = "2.6.1"
dotenv = "0.15.0"
